### ISSUE TITLE
Application not finding the font in the system

### ISSUE THREAD

**Issue by abhaytalreja** [hirohisa/Font-Awesome#4]
I added the Font-Awesome.swift - Looking at the code, it's not able to get the contents of the file. I also tried using the get contents of file but data is always coming as nil.

I also added the font to the info.plist but no luck. Am i missing anything. I tried with .ttf as well as .otf with no luck.

```
class FontManager {
        class func load(fontName: String) {
            if (UIFont.fontNamesForFamilyName(fontName).count > 0) {
                return
            }

            let fontURL = NSBundle.mainBundle().URLForResource(fontName, withExtension: "otf")
            **let data = NSData(contentsOfURL: fontURL!)!**

            let provider = CGDataProviderCreateWithCFData(data)
            let font = CGFontCreateWithDataProvider(provider)!

            var error: Unmanaged<CFError>?
            if !CTFontManagerRegisterGraphicsFont(font, &error) {
                println(error)
            }
        }
    }
```

**Comment by hirohisa** [comment]
Thanks comment, @abhaytalreja .

Do you check "Project" > "Target" > "Copy Bundle Resources" ? And `otf` file is imported?

**Comment by hirohisa** [comment]
And I fixed by https://github.com/hirohisa/Font-Awesome/pull/5 about crashing this issue. you try to build with new file.

**Comment by abhaytalreja** [comment]
It worked, 1 your code fix didn't break the application, now it handled the null pointer. I was missing the otf file in the Bundle resources.
