### ISSUE TITLE
'UIFont.Type' does not have a member named 'fontAwesome'

### ISSUE THREAD

**Issue by wstudios** [hirohisa/Font-Awesome#6]
I copied both the Font-Awesome folder and the FontAwesome.swift to the projects folder but when i tried to use one of the example I received the above error.
This is the example:
let label = UILabel(frame: frame)
label.font = UIFont.fontAwesome(size: 40)
label.text = String.fontAwesome(unicode: 0xf092) // f092 = fa-github-square

I tried it on others with the same error.

**Comment by hirohisa** [comment]
Do you check "Project" > "Target" > "Copy Bundle Resources" ? And otf file is imported? https://github.com/hirohisa/Font-Awesome/issues/4
